-
  name: install apache
  hosts: target1
  tasks:
    - name: install apache
      package:
        name: httpd
        state: present

    - name: start http service
      service:
          name: httpd
          state: started
          enabled: yes
