-
  name: install apache
  hosts: 192.168.215.4
  become_user: root
  tasks:
    - name: install apache
      package:
        name: httpd
        state: present

    - name: start http service
      service:
          name: httpd
          state: started
          enabled: yes
